[package]
name = "reactor"
version = "0.1.0"
authors = ["Rick Richardson <rick.richardson@gmail.com>"]

[features]
unstable=[]

[dependencies]

log="*"
iobuf="*"
time="*"

[dependencies.mio]
git = "https://github.com/carllerche/mio"
